# *****************************服务端口*****************************
server:
  port: 18010
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

# ****************************开启feign日志级别及配置****************************
feign:
  sentinel:
    enabled: true
  client:
    config:
      #微服务实例
      default:
        readTimeout: 60000
        connectTimeout: 60000
        loggerLevel: full
  httpclient:
    max-connections: 100
    max-connections-per-route: 50
    #让feign 使用apache httpclient 做请求；而不是默认url
    enabled: true
    #开启请求压缩
    compression:
      request:
        enabled: true
      response:
        enabled: true
ribbon:
  eager-load:
    enabled: true
    clients:
      - api-platform
# *****************************开启所有请求端点*****************************

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        endpoint:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.lanswon.*: debug
    io.lettuce.core.protocol: error
    com.alibaba.nacos.client.naming.*: error
  path: /log/spring-alibaba/ssm

# ****************************mybatis映射****************************
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*.xml

spring:
  mvc:
    servlet:
      load-on-startup: 0
  application:
    name: swat-sysmanage
  profiles:
    active: dev